'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Briscola.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property assecoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assecoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assobastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assobastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assodenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assodenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assospade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assospade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Carte_piacentine_al_completo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carte_piacentine_al_completo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cartestravinte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartestravinte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cavallobastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cavallobastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cavallocoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cavallocoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cavallodenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cavallodenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cavallospade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cavallospade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cinquebastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cinquebastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cinquecoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cinquecoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cinquedenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cinquedenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cinquespade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cinquespade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cvinte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cvinte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DEFINITIVO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DEFINITIVO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duebastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duebastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duecoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duecoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duedenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duedenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duespade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duespade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fantebastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fantebastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fantecoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fantecoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fantedenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fantedenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fantespade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fantespade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mazzo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mazzo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mazzo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mazzo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mazzo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mazzo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quattrobastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quattrobastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quattrocoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quattrocoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quattrodenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quattrodenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quattrospade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quattrospade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rebastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rebastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property recoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property respade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("respade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property retro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seibastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seibastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seicoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seicoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seidenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seidenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seispade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seispade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settebastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settebastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settecoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settecoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settedenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settedenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settespade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settespade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sfondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sfondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trebastoni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trebastoni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trecoppe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trecoppe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tredenari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tredenari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trespade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trespade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
